import type { Metadata } from "next";
import { Inter,Hanken_Grotesk } from "next/font/google";
import NavBar from "./component/NavBar";
import Footer from "./component/Footer";
import "./globals.css";
import "../app/style/fadeAnimation.css";
import "./font.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Profile Business Solution",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link
          href="https://unpkg.com/aos@2.3.1/dist/aos.css"
          rel="stylesheet"
        />
        {/* font hanken grotesk  */}
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link
          href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:ital,wght@0,463;1,463&display=swap"
          rel="stylesheet"
          /> */}



<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,200..800&display=swap" rel="stylesheet"/>


<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Onest:wght@100..900&display=swap" rel="stylesheet"/>

          {/* font hanken grotesk  */}
      </head>
      <body className="bg-white">
        <NavBar />
        {children}
        <Footer />
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js" async></script>
        <script>{`AOS.init()`}</script>
      </body>
    </html>
  );
}
